# Golangci-lint configuration for Kubernetes operators
#
# This configuration provides sensible defaults for operator development.
# Place at the root of your project as .golangci.yml

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Which dirs to skip
  skip-dirs:
    - bin
    - vendor
    - tmp
    - .git

  # Which files to skip
  skip-files:
    - ".*\\.pb\\.go$"
    - "zz_generated.*\\.go$"

output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate
  format: colored-line-number

  # Print lines of code with issue
  print-issued-lines: true

  # Print linter name in the end of issue text
  print-linter-name: true

  # Make issues output unique by line
  uniq-by-line: true

  # Sort results by: filepath, line and column
  sort-results: true

linters:
  # Disable all linters
  disable-all: true

  # Enable specific linters
  enable:
    # Bugs
    - gofmt          # Check formatting
    - govet          # Reports suspicious constructs
    - errcheck       # Check for unchecked errors
    - staticcheck    # Go static analysis
    - unused         # Check for unused constants, variables, functions and types
    - gosimple       # Simplify code
    - ineffassign    # Detect ineffectual assignments

    # Style
    - misspell       # Find commonly misspelled English words
    - gocyclo        # Compute cyclomatic complexities
    - godot          # Check if comments end in a period
    - gocritic       # Provides many diagnostics

    # Complexity
    - gocognit       # Compute cognitive complexities
    - goconst        # Find repeated strings that could be replaced by a constant

    # Security
    - gosec          # Inspect source code for security problems

    # Performance
    - prealloc       # Find slice declarations that could potentially be preallocated

  # Don't enable:
  # - goimports      # Use goimports separately or in editor
  # - lll            # Line length limit (too strict)
  # - dupl           # Duplicate code detection (can be noisy)
  # - goerr113       # Dynamic error checking (too strict)

linters-settings:
  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - shadow      # Shadowing variables is sometimes useful

  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`
    check-type-assertions: true

    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`
    check-blank: false

  staticcheck:
    # Select specific checks
    checks: ["all"]

  gocyclo:
    # Minimal code complexity to report
    min-complexity: 15

  gocognit:
    # Minimal code complexity to report
    min-complexity: 20

  goconst:
    # Minimal length of string constant
    min-len: 3

    # Minimum occurrences of constant string count to trigger issue
    min-occurrences: 3

    # Ignore test files
    ignore-tests: true

  misspell:
    # Correct spellings using locale preferences
    locale: US

  godot:
    # Check that each sentence starts with a capital letter
    capital: true

  prealloc:
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
    simple: true
    range-loops: true
    for-loops: false

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues
  new: false

  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck

    # Exclude known linters from partially hard-vendored code
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Independently of option `exclude` we use default exclude patterns
  exclude-use-default: false
